name: Build APK

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Buildozer
        run: |
          sudo apt update
          sudo apt install -y zip unzip openjdk-17-jdk
          python -m pip install --upgrade pip
          pip install buildozer cython

      - name: Build APK
        run: |
          yes | buildozer android debug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: Zahala-Factory-Control-APK
          path: bin/*.apk
